# Generated by Django 5.2.1 on 2025-06-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cocktail Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('base_alcohol', models.CharField(choices=[('None', 'None'), ('Gin', 'Gin'), ('Vodka', 'Vodka'), ('Rum', 'Rum'), ('Tequila', 'Tequila'), ('Whisky', 'Whisky')], max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.category')),
                ('ingredients', models.ManyToManyField(to='bar.cocktailingredient')),
            ],
            options={
                'verbose_name_plural': 'Cocktails',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.category')),
            ],
            options={
                'verbose_name_plural': 'Food',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flavour', models.CharField(max_length=150)),
                ('tobacco', models.CharField(choices=[('None', 'None'), ('Light', 'Light'), ('Dark', 'Dark')], max_length=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.category')),
            ],
            options={
                'verbose_name_plural': 'Water Pipes',
                'ordering': ['name'],
            },
        ),
    ]
