# Generated by Django 5.2.3 on 2025-06-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
