# Generated by Django 5.2.3 on 2025-06-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_alter_cocktail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
